### Создать нового автора
POST http://localhost:3000/authors
Content-Type: application/json

{
  "name": "Первый Автор",
  "nickname": "first_author",
  "link": "http://localhost:3000/link"
}

###

### Запустить парсинг для профиля
POST http://localhost:3000/parse
Content-Type: application/json

{
  "nickname": "nik_beton"
}